### ISSUE TITLE
Error message "undefined method helper_plugin_translation::getTransItem()" after update

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [splitbrain/dokuwiki-plugin-translation#280]
Hi,
after updating to the current version, I get the following error message when I open a translated page:
```
2023-02-02 08:16:00
Error: Call to undefined method helper_plugin_translation::getTransItem()
/var/www/html/wiki/lib/tpl/bootstrap3/tpl/translation.php(31)
#0 /var/www/html/wiki/lib/tpl/bootstrap3/tpl/navbar.php(89): include_once()
#1 /var/www/html/wiki/lib/tpl/bootstrap3/main.php(51): require_once('/var/www/html/w...')
#2 /var/www/html/wiki/inc/actions.php(27): include('/var/www/html/w...')
#3 /var/www/html/wiki/doku.php(126): act_dispatch()
#4 {main}
```
I've posted the same issue at the template page: [#584](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues/584)

Regards
Juergen

**Comment by splitbrain** [comment]
Hmm I thought about readding the function, as a wrapper around the new `prepareLanguageSelectorItem()`, but the output would differ and require changes in the template code anyway, so it's probably better for template authors to directly use `prepareLanguageSelectorItem()`  anyway...

**Comment by LouisOuellet** [comment]
Is there a way within dokuwiki to change the branch for the updates?
