### ISSUE TITLE
Warning: Undefined array key "src" in lib/plugins/translation/action.php on line 100

### ISSUE THREAD

**Issue by bonomani** [splitbrain/dokuwiki-plugin-translation#293]

**Comment by iron-mesh** [comment]
My logs for this error

2023-11-02 07:52:45E_WARNING: Undefined array key "src"S:\domains\wiki\lib\plugins\translation\action.php(100)
    #0 S:\domains\wiki\lib\plugins\translation\action.php(100): dokuwiki\ErrorHandler::errorHandler()
    #1 S:\domains\wiki\inc\Extension\EventHandler.php(80): action_plugin_translation->translateJS()
    #2 S:\domains\wiki\inc\Extension\Event.php(74): dokuwiki\Extension\EventHandler->process_event()
    #3 S:\domains\wiki\inc\Extension\Event.php(132): dokuwiki\Extension\Event->advise_before()
    #4 S:\domains\wiki\inc\Extension\Event.php(199): dokuwiki\Extension\Event->trigger()
    #5 S:\domains\wiki\inc\template.php(364): dokuwiki\Extension\Event::createAndTrigger()
    #6 S:\domains\wiki\lib\tpl\dokuwiki\main.php(21): tpl_metaheaders()
    #7 S:\domains\wiki\inc\actions.php(27): include('S:\\domains\\wiki...')
    #8 S:\domains\wiki\doku.php(126): act_dispatch()
    #9 {main}
